# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-03 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='autocomplete_prefixes',
            field=models.ManyToManyField(blank=True, db_index=True, to='cities_light.City_Name_Prefix'),
        ),
    ]
